name: Analysis

on:
  push:
  pull_request:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.17
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev
          go install golang.org/x/lint/golint@latest
      - name: lint
        run: golint ./...
      - name: vet
        run: go vet ./...
