name: Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.17'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev
      - name: test
        run: |
          go test ./... -race -coverprofile=coverage.txt.tmp -covermode=atomic
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
